// generated by src/lib/vocab/persona/persona.schema.ts

export interface PersonaParams {
	name: string;
}
export type Persona =
	| {
			persona_id: number;
			account_id: number;
			community_id: number;
			type: 'account';
			name: string;
			icon?: string;
			created: Date;
			updated: Date | null;
	  }
	| {
			persona_id: number;
			account_id?: null;
			community_id: number;
			type: 'community';
			name: string;
			icon?: string;
			created: Date;
			updated: Date | null;
	  };

// generated by src/lib/vocab/persona/persona.schema.ts
