import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';

import {services} from '$lib/server/services';

// Outputs a file with services metadata that can be imported from the client.
export const gen: Gen = async ({originId}) => {
	return `
// generated by ${toRootPath(originId)}

// this module is a client-friendly subset of data from '$lib/server/services.ts'

${Array.from(services.values()).reduce(
	(str, service) =>
		str +
		`
export const ${service.name} = {
  name: '${service.name}',
  paramsSchema: ${JSON.stringify(service.paramsSchema)},
  // TODO response schema after merging
};
`,
	'',
)}

  `.trim();
};
