// generated by src/lib/server/servicesMeta.gen.ts

export const read_community = {
	name: 'read_community',
	paramsSchema: {
		additionalProperties: false,
		type: 'object',
		properties: {community_id: {type: 'number'}},
		required: ['community_id'],
	},
	// TODO response schema after merging
};

export const read_communities = {
	name: 'read_communities',
	paramsSchema: {additionalProperties: false, type: 'object', properties: {}},
	// TODO response schema after merging
};

export const create_community = {
	name: 'create_community',
	paramsSchema: {
		additionalProperties: false,
		type: 'object',
		properties: {name: {type: 'string'}, persona_id: {type: 'number'}},
		required: ['name', 'persona_id'],
	},
	// TODO response schema after merging
};

export const create_member = {
	name: 'create_member',
	paramsSchema: {
		$id: 'MemberParams',
		additionalProperties: false,
		type: 'object',
		properties: {persona_id: {type: 'number'}, community_id: {type: 'number'}},
		required: ['persona_id', 'community_id'],
	},
	// TODO response schema after merging
};

export const read_files = {
	name: 'read_files',
	paramsSchema: {
		additionalProperties: false,
		type: 'object',
		properties: {space_id: {type: 'number'}},
		required: ['space_id'],
	},
	// TODO response schema after merging
};

export const create_file = {
	name: 'create_file',
	paramsSchema: {
		additionalProperties: false,
		type: 'object',
		properties: {actor_id: {type: 'number'}, space_id: {type: 'number'}, content: {type: 'string'}},
		required: ['actor_id', 'space_id', 'content'],
	},
	// TODO response schema after merging
};

export const read_space = {
	name: 'read_space',
	paramsSchema: {
		additionalProperties: false,
		type: 'object',
		properties: {space_id: {type: 'number'}},
		required: ['space_id'],
	},
	// TODO response schema after merging
};

export const read_spaces = {
	name: 'read_spaces',
	paramsSchema: {
		additionalProperties: false,
		type: 'object',
		properties: {community_id: {type: 'number'}},
		required: ['community_id'],
	},
	// TODO response schema after merging
};

export const create_space = {
	name: 'create_space',
	paramsSchema: {
		additionalProperties: false,
		type: 'object',
		properties: {
			community_id: {type: 'number'},
			name: {type: 'string'},
			url: {type: 'string'},
			media_type: {type: 'string'},
			content: {type: 'string'},
		},
		required: ['community_id', 'name', 'url', 'media_type', 'content'],
	},
	// TODO response schema after merging
};
