import type {Gen} from '@feltcoop/gro/dist/gen/gen.js';
import {toRootPath} from '@feltcoop/gro/dist/paths.js';

import {services} from '$lib/server/services';

// Outputs a file with services metadata that can be imported from the client.
export const gen: Gen = async ({originId}) => {
	return `
  // generated by ${toRootPath(originId)}
  
import type {AnySchema} from 'ajv';

// this module is a client-friendly subset of data from '$lib/server/services.ts'

export interface ServiceMeta {
  name: string;
  route: {
    path: string;
    method: string;
  };
  paramsSchema: AnySchema;
  responseSchema: AnySchema;
}

${Array.from(services.values()).reduce(
	(str, service) =>
		str +
		`
export const ${service.name}: ServiceMeta = {
  name: '${service.name}',
  route: {
    path: '${service.route.path}',
    method: '${service.route.method}',
  },
  paramsSchema: ${JSON.stringify(service.paramsSchema)},
  responseSchema: ${JSON.stringify(service.responseSchema)},
};
`,
	'',
)}

  `.trim();
};
