// generated by src/infra/setupTask.schema.ts

export interface SetupTaskArgs {
	/**
	 * if true, logs the generated script instead of executing it
	 */
	dry?: boolean;
}

// generated by src/infra/setupTask.schema.ts
