# This workflow will do a clean install of node dependencies,
# build the source code, and run tests across different versions of node.
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16]

    services:
      # Postgres config taken from GitHub Actions help docs:
      # https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
      postgres:
        image: postgres
        env:
          POSTGRES_DB: felt
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npx gro check
      - run: npx gro build
